### ISSUE TITLE
Can't create model with only id

### ISSUE THREAD

**Issue by grahamburgsma** [vapor/fluent-sqlite-driver#21]
During development I came across this issue.

The model:
```
final class Game: SQLiteModel {

    var id: Int?
}
```

The code:
`Game().create(on: req)`

The error:
```
INSERT INTO "Game" VALUES () []
[logging] near ")": syntax error
```

**Comment by Strobocop** [comment]
@tanner0101 Can confirm that this also happens in the following example  where all other values are optional, in case that effects the fix:

`
final class ExampleModel: SQLiteModel {
    var id: Int?
    var stringValue: String?
}
`
