### ISSUE TITLE
typeMismatch when reading a number stored as string

### ISSUE THREAD

**Issue by alexqzd** [vapor/fluent-sqlite-driver#71]
### Describe the bug

I have a model with its ID stored as a String representing an hex value. When I read an item where the ID string is just numbers I get `[ ERROR ] invalid field: id type: Optional<String> error: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [], debugDescription: "Could not initialize String from 12345.", underlyingError: nil))`

### To Reproduce

To reproduce add a model with a String as ID
```swift
final class Device: Model, Content {
    
    typealias IDValue = String
    
    // Name of the table or collection.
    static let schema = "devices"
    
    // Unique identifier for this Device.
    @ID(custom: "id")
    var id: String?
    
    // The device's name.
    @Field(key: "name")
    var name: String?
    
    // Creates a new, empty Device.
    init() { }
    
    // Creates a new Device with all properties set.
    init(id: String, name: String) {
        self.id = id
        self.name = name
    }
} 
```

Then save a device using
```swift
let newDevice = Device(id: "12345", name: "myDevice")
newDevice.create(on: req.db).whenSuccess({})
```

Finally query that ID
```swift
let deviceOnDB: EventLoopFuture<Device?> = Device.find("12345", on: req.db)
deviceOnDB.whenComplete { (result) in
    switch result {
    case .success(let device):
        if let device = device {
            req.logger.info("Success")
        }
    case .failure(let error):
            req.logger.error("Failure")
    }
}
```

### Expected behavior

The query returns the saved device

### Actual behavior
This error message is sent to me:
```
[ ERROR ] invalid field: id type: Optional<String> error: typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [], debugDescription: "Could not initialize String from 12345.", underlyingError: nil))
```
If I query the database myself I can get the saved objet just fine
### Environment

*Framework: 4.30.0
*Toolbox: 18.3.0
*OS version: macOS 11.1

### Additional context
If I save an ID containing a letter like "12345A" it does work.

**Comment by 0xTim** [comment]
@alexqzd just to confirm - how are you preparing the table in the migration and setting the ID column?

**Comment by alexqzd** [comment]
Hi @0xTim, I'm preparing the table like this: 
```swift
struct CreateDeviceDB: Migration {
    // Prepares the database for storing Devices models.
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.schema("devices")
            .id()
            .field("name", .string)
            .create()
    }
    
    // Optionally reverts the changes made in the prepare method.
    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.schema("devices").delete()
    }
}
```

**Comment by 0xTim** [comment]
Hmm if you change `.id()` to `.field("id", .int, .identifier(auto: false))` does that help?

**Comment by alexqzd** [comment]
I changed it to `.field("id", .string, .identifier(auto: false))` since I want it to be stored in an human-readable format and now it works as expected. Thank you!

**Comment by 0xTim** [comment]
Sorry ha I meant `.string` 😅 - glad it works!
