### ISSUE TITLE
Unable to delete columns using Schema Builder/Migration

### ISSUE THREAD

**Issue by grey280** [vapor/fluent-sqlite-driver#72]
### Describe the bug

I am attempting to write a migration to delete a column. However, in testing, I receive `previousError(SQLite only supports adding columns in ALTER TABLE statements.)` when I attempt to run the migration, and the database is not updated.

### To Reproduce
In reduced form:
```swift
struct Migration1: Migration { 
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.schema("my_table")
            .field("field", .double, .required)
            .field("other_field", .double)
            .create()
    }
    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.schema("my_table").delete()
    }
}

struct Migration2: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        database.schema("my_table")
            .deleteField("field")
            .update()
    }
    func revert(on database: Database) -> EventLoopFuture<Void> {
        database.schema("my_table")
            .field("field", .double, .required)
            .update()
    }
}
```

1. Define the two migrations above and attempt to run them in order.

### Expected behavior

The end result for the table "my_table" should be a schema of a single column named "other_field".

### Environment
Grabbing relevant sections from my Package.resolved:
```json
     {
        "package": "fluent",
        "repositoryURL": "https://github.com/vapor/fluent.git",
        "state": {
          "branch": null,
          "revision": "855cd81cd129675dcb9adadeca2286281dbc0190",
          "version": "4.1.0"
        }
      },
      {
        "package": "fluent-kit",
        "repositoryURL": "https://github.com/vapor/fluent-kit.git",
        "state": {
          "branch": null,
          "revision": "86ebecdb98981b7a242746209b4335770bf0bd11",
          "version": "1.10.2"
        }
      },
     {
        "package": "fluent-sqlite-driver",
        "repositoryURL": "https://github.com/vapor/fluent-sqlite-driver.git",
        "state": {
          "branch": null,
          "revision": "6f29f6f182c812075f09c7575c18ac5535c26824",
          "version": "4.0.1"
        }
      },
      {
        "package": "vapor",
        "repositoryURL": "https://github.com/vapor/vapor.git",
        "state": {
          "branch": null,
          "revision": "5148f02e42149f73f6616452062cf96b64afbda6",
          "version": "4.36.2"
        }
      }
```

* Vapor Framework version: 4.36.2
* Vapor Toolbox version: Unknown; `vapor --version` yields `Error: Unknown command '--version'`
* OS version: macOS 11.2.3; Xcode 12.4 (12D4e)

**Comment by grey280** [comment]
`brew list--versions vapor` says I have `vapor 18.0.0` as the Toolbox version.

**Comment by 0xTim** [comment]
@grey280 as the error states, SQLite does not support deleting a column. In fact, judging by [StackOverflow](https://stackoverflow.com/a/8442173/1823705) it's simply not possible to delete a column in SQLite. The workaround is to create a new table without the column you want to delete and copy all the data over. Unfortunately that's a little out of scope for Fluent as it doesn't have all the information it needs with just the `.deleteField("field")` call so you'll need to write a raw SQL migration.

As an aside, the latest toolbox is 18.3.1 so make sure you update to that. You might need to remove the Vapor tap to be able to see it
