### ISSUE TITLE
Getting a pragma value

### ISSUE THREAD

**Issue by adamnemecek** [vapor/fluent-sqlite-driver#79]
I'm having a hard time figuring out how to get a pragma value out of SQLite using Fluent. Any pointers?

**Comment by 0xTim** [comment]
@adamnemecek was this solved in Discord?

**Comment by gwynne** [comment]
```swift
try await (req.db as! any SQLDatabase).raw("PRAGMA some_pragma_or_other").first()?.decode(column: "some_pragma_or_other", as: Int.self)
```
See also https://github.com/vapor/sqlite-kit/blob/main/Tests/SQLiteKitTests/SQLiteKitTests.swift#L92-L93
