### ISSUE TITLE
Foreign Key corruption error when performing async calls

### ISSUE THREAD

**Issue by kuhl** [vapor/fluent-sqlite-driver#93]
### Describe the issue

SQLite will report a foreign key corruption error in some objects inserted with asynchronous method and throws error on an attempt to delete.

### Vapor version

Fluent-Kit 1.48.0

### Operating system and version

OS 14.4.1, Ubuntu 22.04

### Swift version

5.9.2, 5.10

### Steps to reproduce

Asynchronously add several records on the same table.
Request deletion of objects. At least one should uncover the foreign key corruption error.

### Additional notes

I'm running the sqlite database in memory as a part of unit testing. Using Hummingbird framework.

**Comment by 0xTim** [comment]
Can you show the code of how you're saving and deleting objects?

**Comment by kuhl** [comment]
Not your bug. It was mine after a refactor.
